- name: Deploy HTML content
  hosts: webservers
  become: true

  tasks:
    - name: Copy HTML file to web server
      ansible.builtin.copy:
        src: src/index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Ensure Nginx is installed
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true


